### ISSUE TITLE
Checkout not Working After Update from Version 1.13.1 to 2.0.0

### ISSUE THREAD

**Issue by onlyindia** [hps/heartland-woocommerce-plugin#181] opened 2022-08-06 07:24 UTC
We have started loosing orders since your plugin auto updated yesterday.

When we click on button "Place Order” on the ckeck out page then it doesn’t do anything.

Woocommerce version 6.5.1. 

Pls note: there is no issue with other plugins or theme, I disalbled all and tested but still same issue.

Pls resolve the issue asap.

**Comment by tflight** [comment] 2022-08-06 12:33
I can confirm this is happening my client as well across all environments and plugin/theme combinations.

**Comment by ahswebster** [comment] 2022-08-10 12:57
Same issue. The boxes for CC input are gone. Latest WP version. Disabled all other scripts on the page. 

Where can you get the 1.13.1 stable version?

**Comment by tflight** [comment] 2022-08-10 13:07
@ahswebster I suspect [this is the link](https://github.com/hps/heartland-woocommerce-plugin/archive/c05c8fcee27a74a40c1cca41fbd7268bb6f3a369.zip) you will want, based on the [commit history](https://github.com/hps/heartland-woocommerce-plugin/commits/master) this takes you back to the commit on April 12.

**Comment by securesubmit-buildmaster** [comment] 2022-08-10 14:33
We're sorry to hear of these issues. If anyone would like to provide a link to their site(s) so that we can review we'd be happy to. You can also reach out to us directly at Developers@heartland.us

**Comment by ahswebster** [comment] 2022-08-10 14:54
> @ahswebster I suspect [this is the link](https://github.com/hps/heartland-woocommerce-plugin/archive/c05c8fcee27a74a40c1cca41fbd7268bb6f3a369.zip) you will want, based on the [commit history](https://github.com/hps/heartland-woocommerce-plugin/commits/master) this takes you back to the commit on April 12.

Thank you, that worked. I rolled it back and turned off automatic plugin updates for this.

**Comment by securesubmit-buildmaster** [comment] 2022-08-18 14:55
Closing since we were unable to obtain any information to investigate. Please open a new issue with additional details or reach out to our development team directly at developers@heartland.us

**Closed by securesubmit-buildmaster** 2022-08-18 14:55 UTC
